BASE_COST = 10000
# costs ordered by curent priorities
PENALTY_MISSING_WEEKEND_SHIFT = 1000
PENALTY_NOT_PREFERRED_SHIFTS = 100
PENALTY_EXCESS_WEEKEND_SHIFT = 100
PENALTY_MODIFIER_WILLING = 10
PENALTY_WRONG_FREQUENCY = 1

COST_VOID = 100 * BASE_COST # unassigned shifts penalty


DEFAULT_MIN = 0
NO_PREFERENCE = -1
DEFAULT_PREFERRED = NO_PREFERENCE
DEFAULT_MAX_SHIFTS = 10000
