# BASE_COST = 1250
# # costs ordered by curent priorities
# PENALTY_MISSING_WEEKEND_SHIFT = 250
# PENALTY_NOT_PREFERRED_SHIFTS = 50
# PENALTY_EXCESS_WEEKEND_SHIFT = 50
# PENALTY_MODIFIER_WILLING = 10
# PENALTY_WRONG_FREQUENCY = 1

# COST_VOID = 10 * BASE_COST # unassigned shifts penalty

BASE_COST = 15
# costs ordered by curent priorities
PENALTY_MISSING_WEEKEND_SHIFT = 7
PENALTY_NOT_PREFERRED_SHIFTS = 4
PENALTY_EXCESS_WEEKEND_SHIFT = 4
PENALTY_MODIFIER_WILLING = 1
PENALTY_WRONG_FREQUENCY = 0.1

COST_VOID = 10 * BASE_COST # unassigned shifts penalty


DEFAULT_MIN = 0
NO_PREFERENCE = -1
DEFAULT_PREFERRED = NO_PREFERENCE
DEFAULT_MAX_SHIFTS = 99
